## Importing packages

In [380]:
# Standard Packages
import numpy as np
import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats

from lets_plot import *
LetsPlot.setup_html()
import matplotlib. pyplot as plt

In [381]:
v_dem = pd.read_csv('V-Dem-CY-FullOthers-v15_csv/V-Dem-CY-Full+Others-v15.csv')

/var/folders/jv/j3rkxm0x5jxcjs_kt7l82f9c0000gn/T/ipykernel_5195/3464300304.py:1: DtypeWarning: Columns (364,365,366,399,804,836,837,924,1240,1257,1486,3094,3168,3169,3341,3342,3344,3345,3347,3350,3352) have mixed types. Specify dtype option on import or set low_memory=False.

In [382]:
v_dem.shape

(27913, 4607)

In [383]:
vdem = v_dem[[
    # for identification 
    'country_name', 
    'country_text_id',
    'year',
    'e_regiongeo',
    # dependent variables
    'v2x_cspart', # civil society participation index interval
    'v2xcs_ccsi', # core civil society index ordinal
    'v2x_partipdem', # participatory democracy index ordinal
    'v2csprtcpt', # civil society participatory environment ordinal
    # independent variables
    'v2x_polyarchy', # electoral democracy index ordinal
    'v2x_libdem', # liberal democracy index ordinal
    'v3elcomvot', # compulsory voting ordinal
    'v2x_api', # Additive polyarchy index ordinal
    'v2xdd_dd', # direct popular vote ordinal
    'v2x_freexp_altinf', # freedom of expression
    'v2xel_frefair', # free and fair elections
    'v2x_egaldem', # egalitarian democracy index ordinal
    'v2x_regime', # regimes of the world
    'v2smgovfilprc', # government filtering in practice
    'v2smgovsmcenprc', # government social media censorship in practice
    'v2smonper', # online media perspectives ordinal - do major domestic online media outlets represent a wide range of views?
    ]].copy()

In [384]:
vdem

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,v3elcomvot,v2x_api,v2xdd_dd,v2x_freexp_altinf,v2xel_frefair,v2x_egaldem,v2x_regime,v2smgovfilprc,v2smgovsmcenprc,v2smonper
0,Mexico,MEX,1789,17,0.031,0.055,0.006,-2.351,0.028,0.044,NaN,0.056,NaN,0.175,0.000,NaN,NaN,NaN,NaN,NaN
1,Mexico,MEX,1790,17,0.031,0.055,0.006,-2.351,0.028,0.044,NaN,0.056,NaN,0.175,0.000,NaN,NaN,NaN,NaN,NaN
2,Mexico,MEX,1791,17,0.031,0.055,0.006,-2.351,0.028,0.044,NaN,0.056,NaN,0.175,0.000,NaN,NaN,NaN,NaN,NaN
3,Mexico,MEX,1792,17,0.031,0.055,0.006,-2.351,0.028,0.044,NaN,0.056,NaN,0.175,0.000,NaN,NaN,NaN,NaN,NaN
4,Mexico,MEX,1793,17,0.031,0.055,0.006,-2.351,0.028,0.044,NaN,0.056,NaN,0.175,0.000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27908,Piedmont-Sardinia,SPD,1857,3,0.194,0.278,0.063,-0.672,0.205,0.134,-0.659,0.411,NaN,0.617,0.430,NaN,NaN,NaN,NaN,NaN
27909,Piedmont-Sardinia,SPD,1858,3,0.194,0.278,0.063,-0.672,0.206,0.133,NaN,0.412,NaN,0.617,0.431,NaN,NaN,NaN,NaN,NaN
27910,Piedmont-Sardinia,SPD,1859,3,0.194,0.278,0.063,-0.672,0.206,0.133,NaN,0.412,NaN,0.617,0.431,NaN,NaN,NaN,NaN,NaN
27911,Piedmont-Sardinia,SPD,1860,3,0.194,0.278,0.062,-0.672,0.210,0.135,-0.639,0.420,NaN,0.617,0.471,NaN,NaN,NaN,NaN,NaN
27912,Piedmont-Sardinia,SPD,1861,3,0.330,0.278,0.075,-0.672,0.210,0.135,NaN,0.419,NaN,0.617,0.472,NaN,NaN,NaN,NaN,NaN

In [385]:
vdem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27913 entries, 0 to 27912
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country_name       27913 non-null  object
 1   country_text_id    27913 non-null  object
 2   year               27913 non-null  int64
 3   e_regiongeo        27913 non-null  int64
 4   v2x_cspart         27286 non-null  float64
 5   v2xcs_ccsi         27516 non-null  float64
 6   v2x_partipdem      26162 non-null  float64
 7   v2csprtcpt         27262 non-null  float64
 8   v2x_polyarchy      26775 non-null  float64
 9   v2x_libdem         25530 non-null  float64
 10  v3elcomvot         1467 non-null   float64
 11  v2x_api            26775 non-null  float64
 12  v2xdd_dd           19546 non-null  float64
 13  v2x_freexp_altinf  27377 non-null  float64
 14  v2xel_frefair      27791 non-null  float64
 15  v2x_egaldem        19488 non-null  float64
 16  v2x_regime         19581 non-null  float64
 17  v2smgovfilprc      4457 non-null   float64
 18  v2smgovsmcenprc    4457 non-null   float64
 19  v2smonper          4457 non-null   float64
dtypes: float64(16), int64(2), object(2)
memory usage: 4.3+ MB

In [386]:
vdem[vdem['v3elcomvot'].notna()]['year'].describe()

count    1467.000000
mean     1874.567825
std        32.861963
min      1789.000000
25%      1851.000000
50%      1876.000000
75%      1900.000000
max      2010.000000
Name: year, dtype: float64

In [387]:
vdem[vdem['v2xdd_dd'].notna()]['year'].describe()

count    19546.000000
mean      1965.541850
std         35.766919
min       1900.000000
25%       1935.000000
50%       1967.000000
75%       1997.000000
max       2024.000000
Name: year, dtype: float64

In [388]:
vdem[vdem['v2x_egaldem'].notna()]['year'].describe()

count    19488.000000
mean      1965.668411
std         35.736092
min       1900.000000
25%       1935.000000
50%       1967.000000
75%       1997.000000
max       2024.000000
Name: year, dtype: float64

In [389]:
vdem[vdem['v2x_regime'].notna()]['year'].describe()

count    19581.000000
mean      1965.410194
std         35.851126
min       1900.000000
25%       1935.000000
50%       1967.000000
75%       1997.000000
max       2024.000000
Name: year, dtype: float64

#### Specifying region

In [390]:
south_asia = ['India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 
              'Nepal', 'Bhutan', 'Maldives']
southeast_asia = ['Singapore', 'Thailand', 'Indonesia', 'Philippines',
                  'Malaysia', 'Cambodia', 'Vietnam', 'Laos', 
                  'Burma/Myanmar', 'Timor-Leste']
east_asia = ['Japan', 'South Korea', 'Taiwan', 'Mongolia', 'China', 'Hong Kong']

core_countries = south_asia + southeast_asia + east_asia

In [391]:
asian_vdem = vdem[vdem['country_name'].isin(core_countries)].copy()

In [392]:
asian_vdem['country_name'].unique()

array(['Japan', 'Burma/Myanmar', 'Bangladesh', 'Pakistan', 'Vietnam',
       'India', 'South Korea', 'Philippines', 'Taiwan', 'Thailand',
       'Bhutan', 'Cambodia', 'Indonesia', 'Nepal', 'Timor-Leste',
       'Maldives', 'Mongolia', 'China', 'Laos', 'Sri Lanka', 'Hong Kong',
       'Malaysia', 'Singapore'], dtype=object)

In [393]:
wdi = pd.read_csv('WorldBankData.csv')

In [394]:
year_cols = []

for col in wdi.columns:
    if col.startswith("19") or col.startswith("20"):
        year_cols.append(col)

year_cols

['1975 [YR1975]',
 '1976 [YR1976]',
 '1977 [YR1977]',
 '1978 [YR1978]',
 '1979 [YR1979]',
 '1980 [YR1980]',
 '1981 [YR1981]',
 '1982 [YR1982]',
 '1983 [YR1983]',
 '1984 [YR1984]',
 '1985 [YR1985]',
 '1986 [YR1986]',
 '1987 [YR1987]',
 '1988 [YR1988]',
 '1989 [YR1989]',
 '1990 [YR1990]',
 '1991 [YR1991]',
 '1992 [YR1992]',
 '1993 [YR1993]',
 '1994 [YR1994]',
 '1995 [YR1995]',
 '1996 [YR1996]',
 '1997 [YR1997]',
 '1998 [YR1998]',
 '1999 [YR1999]',
 '2000 [YR2000]',
 '2001 [YR2001]',
 '2002 [YR2002]',
 '2003 [YR2003]',
 '2004 [YR2004]',
 '2005 [YR2005]',
 '2006 [YR2006]',
 '2007 [YR2007]',
 '2008 [YR2008]',
 '2009 [YR2009]',
 '2010 [YR2010]',
 '2011 [YR2011]',
 '2012 [YR2012]',
 '2013 [YR2013]',
 '2014 [YR2014]',
 '2015 [YR2015]',
 '2016 [YR2016]',
 '2017 [YR2017]',
 '2018 [YR2018]',
 '2019 [YR2019]',
 '2020 [YR2020]',
 '2021 [YR2021]',
 '2022 [YR2022]',
 '2023 [YR2023]',
 '2024 [YR2024]']

In [395]:
wdi

,Country Name,Country Code,Series Name,Series Code,1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],1980 [YR1980],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Japan,JPN,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,16333.6748183565,16801.9250305932,17370.6165468128,18120.7284269863,18953.3339136853,19334.3747441799,...,34960.6393843385,35242.199377148,35861.9728545672,36138.5290824814,36043.7844013518,34642.9718743239,35741.1601062924,36238.3294895302,36952.5150709861,37152.5636003552
1,Japan,JPN,Individuals using the Internet (% of population),IT.NET.USER.ZS,..,..,..,..,..,..,...,91.058,93.1827,91.7265,88.7464,92.7304,90.2195,82.9141,84.9234,86.9815,..
2,Japan,JPN,Urban population (% of total population),SP.URB.TOTL.IN.ZS,75.8511067264535,75.9718496490584,76.0333398797102,76.0764616511381,76.1171567691576,76.172396260342,...,91.3532644103625,91.4541254852142,91.5498419685883,91.6377318609728,91.7164207898107,91.7809926267889,91.8741049279527,91.9776532428406,92.0826903891473,92.1901718034531
3,Japan,JPN,"Population, total",SP.POP.TOTL,111573000,112775000,113872000,114913000,115890000,116807000,...,127141000,127076000,126972000,126811000,126633000,126261000,125681593,125124989,124516650,123975371
4,Japan,JPN,"Literacy rate, adult total (% of people ages 1...",SE.ADT.LITR.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,Last Updated: 01/28/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [396]:
wdi_long = wdi.melt(
    id_vars=['Country Name', 'Country Code', 'Series Name'],
    value_vars=year_cols,
    var_name='year',
    value_name='value'
)

wdi_long

,Country Name,Country Code,Series Name,year,value
0,Japan,JPN,GDP per capita (constant 2015 US$),1975 [YR1975],16333.6748183565
1,Japan,JPN,Individuals using the Internet (% of population),1975 [YR1975],..
2,Japan,JPN,Urban population (% of total population),1975 [YR1975],75.8511067264535
3,Japan,JPN,"Population, total",1975 [YR1975],111573000
4,Japan,JPN,"Literacy rate, adult total (% of people ages 1...",1975 [YR1975],..
...,...,...,...,...,...
6845,NaN,NaN,NaN,2024 [YR2024],NaN
6846,NaN,NaN,NaN,2024 [YR2024],NaN
6847,NaN,NaN,NaN,2024 [YR2024],NaN
6848,Data from database: World Development Indicators,NaN,NaN,2024 [YR2024],NaN
6849,Last Updated: 01/28/2026,NaN,NaN,2024 [YR2024],NaN

In [397]:
wdi_long['year'] = wdi_long['year'].str[:4].astype(int)
wdi_long

,Country Name,Country Code,Series Name,year,value
0,Japan,JPN,GDP per capita (constant 2015 US$),1975,16333.6748183565
1,Japan,JPN,Individuals using the Internet (% of population),1975,..
2,Japan,JPN,Urban population (% of total population),1975,75.8511067264535
3,Japan,JPN,"Population, total",1975,111573000
4,Japan,JPN,"Literacy rate, adult total (% of people ages 1...",1975,..
...,...,...,...,...,...
6845,NaN,NaN,NaN,2024,NaN
6846,NaN,NaN,NaN,2024,NaN
6847,NaN,NaN,NaN,2024,NaN
6848,Data from database: World Development Indicators,NaN,NaN,2024,NaN
6849,Last Updated: 01/28/2026,NaN,NaN,2024,NaN

In [398]:
wdi_long.rename(columns={
    "Country Name": "country_name",
    "Country Code": "country_text_id"}, inplace=True)

In [399]:
wdi_long['value'] = pd.to_numeric(wdi_long['value'], errors='coerce')

In [400]:
wdi_long

,country_name,country_text_id,Series Name,year,value
0,Japan,JPN,GDP per capita (constant 2015 US$),1975,1.633367e+04
1,Japan,JPN,Individuals using the Internet (% of population),1975,NaN
2,Japan,JPN,Urban population (% of total population),1975,7.585111e+01
3,Japan,JPN,"Population, total",1975,1.115730e+08
4,Japan,JPN,"Literacy rate, adult total (% of people ages 1...",1975,NaN
...,...,...,...,...,...
6845,NaN,NaN,NaN,2024,NaN
6846,NaN,NaN,NaN,2024,NaN
6847,NaN,NaN,NaN,2024,NaN
6848,Data from database: World Development Indicators,NaN,NaN,2024,NaN
6849,Last Updated: 01/28/2026,NaN,NaN,2024,NaN

In [401]:
wdi_wide = wdi_long.pivot_table(
    index=['country_name', 'year'],
    columns='Series Name',
    values='value'
).reset_index()

In [402]:
wdi_wide

Series Name,country_name,year,GDP per capita (constant 2015 US$),Individuals using the Internet (% of population),"Literacy rate, adult total (% of people ages 15 and above)","Population, total","School enrollment, secondary (% gross)",Urban population (% of total population)
0,Bangladesh,1975,373.260374,NaN,NaN,77854351.0,NaN,9.634516
1,Bangladesh,1976,384.509552,NaN,NaN,79855318.0,16.557060,10.551336
2,Bangladesh,1977,385.085520,NaN,NaN,81867264.0,16.674330,11.602706
3,Bangladesh,1978,402.385596,NaN,NaN,83889655.0,NaN,12.699724
4,Bangladesh,1979,411.669267,NaN,NaN,85935072.0,16.942320,13.753491
...,...,...,...,...,...,...,...,...
1095,Viet Nam,2020,3303.169498,70.30,NaN,98079191.0,93.192139,35.570668
1096,Viet Nam,2021,3358.217348,74.21,NaN,98935098.0,92.769021,36.654066
1097,Viet Nam,2022,3617.663115,78.59,96.129997,99680655.0,93.412343,37.547852
1098,Viet Nam,2023,3775.463756,78.08,NaN,100352192.0,NaN,38.129890
1099,Viet Nam,2024,4017.746041,84.15,NaN,100987686.0,NaN,38.490070

In [403]:
wdi_wide['country_name'].unique()

array(['Bangladesh', 'Bhutan', 'Cambodia', 'China',
       'Hong Kong SAR, China', 'India', 'Indonesia', 'Japan',
       'Korea, Rep.', 'Lao PDR', 'Malaysia', 'Maldives', 'Mongolia',
       'Myanmar', 'Nepal', 'Pakistan', 'Philippines', 'Singapore',
       'Sri Lanka', 'Thailand', 'Timor-Leste', 'Viet Nam'], dtype=object)

In [404]:
asian_vdem['country_name'].unique()

array(['Japan', 'Burma/Myanmar', 'Bangladesh', 'Pakistan', 'Vietnam',
       'India', 'South Korea', 'Philippines', 'Taiwan', 'Thailand',
       'Bhutan', 'Cambodia', 'Indonesia', 'Nepal', 'Timor-Leste',
       'Maldives', 'Mongolia', 'China', 'Laos', 'Sri Lanka', 'Hong Kong',
       'Malaysia', 'Singapore'], dtype=object)

In [405]:
wdi_wide['country_name'] = wdi_wide['country_name'].replace({
    'Korea, Rep.' : 'South Korea',
    'Hong Kong SAR, China': 'Hong Kong',
    'Lao PDR' : 'Laos',
    'Viet Nam': 'Vietnam'})

In [406]:
asian_vdem['country_name']=asian_vdem['country_name'].replace({
    'Burma/Myanmar': 'Myanmar'})

In [407]:
merged_data = asian_vdem.merge(wdi_wide, on=['country_name', 'year'], how='left')

In [408]:
merged_data

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,v2x_regime,v2smgovfilprc,v2smgovsmcenprc,v2smonper,GDP per capita (constant 2015 US$),Individuals using the Internet (% of population),"Literacy rate, adult total (% of people ages 15 and above)","Population, total","School enrollment, secondary (% gross)",Urban population (% of total population)
0,Japan,JPN,1789,12,0.040,0.102,0.011,-2.204,0.024,0.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Japan,JPN,1790,12,0.040,0.102,0.011,-2.204,0.026,0.016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Japan,JPN,1791,12,0.040,0.102,0.011,-2.204,0.026,0.016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Japan,JPN,1792,12,0.040,0.102,0.011,-2.204,0.026,0.016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Japan,JPN,1793,12,0.040,0.102,0.011,-2.204,0.026,0.016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3606,Singapore,SGP,2020,13,0.329,0.403,0.102,-0.252,0.400,0.325,...,1.0,-0.384,-0.617,-1.301,59189.703857,92.0043,97.129997,5685807.0,103.115839,100.0
3607,Singapore,SGP,2021,13,0.417,0.403,0.109,-0.252,0.395,0.325,...,1.0,-0.384,-0.617,-1.301,67731.261071,96.9247,97.650002,5453566.0,102.951274,100.0
3608,Singapore,SGP,2022,13,0.417,0.403,0.109,-0.252,0.395,0.324,...,1.0,-0.384,-0.617,-1.301,68218.805334,95.9539,NaN,5637022.0,103.009804,100.0
3609,Singapore,SGP,2023,13,0.386,0.403,0.108,-0.252,0.403,0.331,...,1.0,-0.657,-0.617,-0.851,66167.359630,94.2852,NaN,5917648.0,103.082802,100.0
3610,Singapore,SGP,2024,13,0.386,0.403,0.112,-0.252,0.414,0.343,...,1.0,-0.657,-0.617,-1.155,67706.833615,94.3776,NaN,6036860.0,NaN,100.0

In [409]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3611 entries, 0 to 3610
Data columns (total 26 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   country_name                                                3611 non-null   object
 1   country_text_id                                             3611 non-null   object
 2   year                                                        3611 non-null   int64
 3   e_regiongeo                                                 3611 non-null   int64
 4   v2x_cspart                                                  3611 non-null   float64
 5   v2xcs_ccsi                                                  3611 non-null   float64
 6   v2x_partipdem                                               3548 non-null   float64
 7   v2csprtcpt                                                  3611 non-null   float64
 8   v2x_polyarchy                                               3610 non-null   float64
 9   v2x_libdem                                                  3289 non-null   float64
 10  v3elcomvot                                                  5 non-null      float64
 11  v2x_api                                                     3610 non-null   float64
 12  v2xdd_dd                                                    2701 non-null   float64
 13  v2x_freexp_altinf                                           3611 non-null   float64
 14  v2xel_frefair                                               3611 non-null   float64
 15  v2x_egaldem                                                 2701 non-null   float64
 16  v2x_regime                                                  2701 non-null   float64
 17  v2smgovfilprc                                               575 non-null    float64
 18  v2smgovsmcenprc                                             575 non-null    float64
 19  v2smonper                                                   575 non-null    float64
 20  GDP per capita (constant 2015 US$)                          1060 non-null   float64
 21  Individuals using the Internet (% of population)            666 non-null    float64
 22  Literacy rate, adult total (% of people ages 15 and above)  190 non-null    float64
 23  Population, total                                           1100 non-null   float64
 24  School enrollment, secondary (% gross)                      656 non-null    float64
 25  Urban population (% of total population)                    1100 non-null   float64
dtypes: float64(22), int64(2), object(2)
memory usage: 733.6+ KB

In [410]:
merged_data.drop(columns=['v3elcomvot','Literacy rate, adult total (% of people ages 15 and above)'],inplace=True)

In [411]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3611 entries, 0 to 3610
Data columns (total 24 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   country_name                                      3611 non-null   object
 1   country_text_id                                   3611 non-null   object
 2   year                                              3611 non-null   int64
 3   e_regiongeo                                       3611 non-null   int64
 4   v2x_cspart                                        3611 non-null   float64
 5   v2xcs_ccsi                                        3611 non-null   float64
 6   v2x_partipdem                                     3548 non-null   float64
 7   v2csprtcpt                                        3611 non-null   float64
 8   v2x_polyarchy                                     3610 non-null   float64
 9   v2x_libdem                                        3289 non-null   float64
 10  v2x_api                                           3610 non-null   float64
 11  v2xdd_dd                                          2701 non-null   float64
 12  v2x_freexp_altinf                                 3611 non-null   float64
 13  v2xel_frefair                                     3611 non-null   float64
 14  v2x_egaldem                                       2701 non-null   float64
 15  v2x_regime                                        2701 non-null   float64
 16  v2smgovfilprc                                     575 non-null    float64
 17  v2smgovsmcenprc                                   575 non-null    float64
 18  v2smonper                                         575 non-null    float64
 19  GDP per capita (constant 2015 US$)                1060 non-null   float64
 20  Individuals using the Internet (% of population)  666 non-null    float64
 21  Population, total                                 1100 non-null   float64
 22  School enrollment, secondary (% gross)            656 non-null    float64
 23  Urban population (% of total population)          1100 non-null   float64
dtypes: float64(20), int64(2), object(2)
memory usage: 677.2+ KB

In [412]:
merged_data.to_csv('processed_data.csv',index=False)

In [413]:
merged_from_2000 = merged_data[merged_data['year'] >= 2000]

In [414]:
merged_from_2000

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,v2x_egaldem,v2x_regime,v2smgovfilprc,v2smgovsmcenprc,v2smonper,GDP per capita (constant 2015 US$),Individuals using the Internet (% of population),"Population, total","School enrollment, secondary (% gross)",Urban population (% of total population)
211,Japan,JPN,2000,12,0.739,0.880,0.555,0.718,0.845,0.770,...,0.764,3.0,0.912,1.242,1.280,31430.631130,29.9907,126843000.0,NaN,78.612680
212,Japan,JPN,2001,12,0.739,0.880,0.556,0.718,0.845,0.770,...,0.766,3.0,0.912,1.242,1.280,31476.052067,38.5321,127149000.0,NaN,79.157748
213,Japan,JPN,2002,12,0.739,0.880,0.556,0.718,0.845,0.770,...,0.766,3.0,0.912,1.242,1.280,31416.124177,46.5942,127445000.0,NaN,80.546986
214,Japan,JPN,2003,12,0.739,0.880,0.556,0.718,0.845,0.770,...,0.766,3.0,0.912,1.242,1.280,31830.217585,48.4353,127718000.0,NaN,82.420678
215,Japan,JPN,2004,12,0.739,0.880,0.556,0.718,0.845,0.770,...,0.767,3.0,0.912,1.242,1.280,32515.115802,62.3939,127761000.0,NaN,84.371054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3606,Singapore,SGP,2020,13,0.329,0.403,0.102,-0.252,0.400,0.325,...,0.352,1.0,-0.384,-0.617,-1.301,59189.703857,92.0043,5685807.0,103.115839,100.000000
3607,Singapore,SGP,2021,13,0.417,0.403,0.109,-0.252,0.395,0.325,...,0.349,1.0,-0.384,-0.617,-1.301,67731.261071,96.9247,5453566.0,102.951274,100.000000
3608,Singapore,SGP,2022,13,0.417,0.403,0.109,-0.252,0.395,0.324,...,0.349,1.0,-0.384,-0.617,-1.301,68218.805334,95.9539,5637022.0,103.009804,100.000000
3609,Singapore,SGP,2023,13,0.386,0.403,0.108,-0.252,0.403,0.331,...,0.355,1.0,-0.657,-0.617,-0.851,66167.359630,94.2852,5917648.0,103.082802,100.000000
3610,Singapore,SGP,2024,13,0.386,0.403,0.112,-0.252,0.414,0.343,...,0.362,1.0,-0.657,-0.617,-1.155,67706.833615,94.3776,6036860.0,NaN,100.000000

In [415]:
!pip install xlrd

Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.13/site-packages (2.0.2)

In [416]:
voter_turnout = pd.read_excel('IDEA_voter_turnout.xlsx', header=1)

In [417]:
voter_turnout

,Country,ISO2,ISO3,Date,Parliamentary>Voter Turnout,Parliamentary>Registration,Parliamentary>Voting age population,Parliamentary>Population
0,Afghanistan,AF,AFG,2018‑10‑27,45.23,8843151,18340292,34940837
1,Afghanistan,AF,AFG,2010‑09‑18,35.14,12000000,14191908,29120727
2,Afghanistan,AF,AFG,2005‑09‑18,49.37,12977336,12389532,26334702
3,Armenia,AM,ARM,2021‑06‑20,49.39,2595512,2355287,3011609
4,Armenia,AM,ARM,2018‑12‑09,48.63,2593140,2362422,3038217
...,...,...,...,...,...,...,...,...
244,Viet Nam,VN,VNM,2016‑01‑01,99.26,67500000,68142322,95261021
245,Viet Nam,VN,VNM,2011‑01‑01,99.51,62270778,62610289,90549390
246,Viet Nam,VN,VNM,2007‑01‑01,99.64,-,57459568,86518851
247,Viet Nam,VN,VNM,2002‑01‑01,98.85,49783769,48823294,79939014
248,Yemen,YE,YEM,2003‑01‑01,74.98,8097162,8509723,18701257

In [418]:
voter_turnout['Country'].unique()

array(['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       'Bhutan', 'Cambodia', 'Georgia', 'India', 'Indonesia',
       'Iran, Islamic Republic of', 'Iraq', 'Israel', 'Japan', 'Jordan',
       'Kazakhstan', 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Dem. Republic", 'Lebanon', 'Malaysia', 'Maldives',
       'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan',
       'State of Palestine', 'Philippines', 'Qatar', 'Singapore',
       'Sri Lanka', 'Syrian Arab Republic', 'Taiwan', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Turkey', 'Turkmenistan', 'Uzbekistan',
       'Viet Nam', 'Yemen'], dtype=object)

In [419]:
voter_turnout['Country'] = voter_turnout["Country"].replace({
    "Korea, Republic of": "South Korea",
    "Lao People's Dem. Republic": "Laos",
    "Viet Nam": "Vietnam"})

In [420]:
voter_turnout['Country'].unique()

array(['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       'Bhutan', 'Cambodia', 'Georgia', 'India', 'Indonesia',
       'Iran, Islamic Republic of', 'Iraq', 'Israel', 'Japan', 'Jordan',
       'Kazakhstan', 'South Korea', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal',
       'Oman', 'Pakistan', 'State of Palestine', 'Philippines', 'Qatar',
       'Singapore', 'Sri Lanka', 'Syrian Arab Republic', 'Taiwan',
       'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey', 'Turkmenistan',
       'Uzbekistan', 'Vietnam', 'Yemen'], dtype=object)

In [421]:
south_asia = ['India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 
              'Nepal', 'Bhutan', 'Maldives']
southeast_asia = ['Singapore', 'Thailand', 'Indonesia', 'Philippines',
                  'Malaysia', 'Cambodia', 'Vietnam', 'Laos', 
                  'Myanmar', 'Timor-Leste']
east_asia = ['Japan', 'South Korea', 'Taiwan', 'Mongolia', 'China', 'Hong Kong']

core_countries = south_asia + southeast_asia + east_asia

In [422]:
asia_voter_turnout = voter_turnout[voter_turnout['Country'].isin(core_countries)].copy()

In [423]:
asia_voter_turnout

,Country,ISO2,ISO3,Date,Parliamentary>Voter Turnout,Parliamentary>Registration,Parliamentary>Voting age population,Parliamentary>Population
21,Bangladesh,BD,BGD,2024‑01‑07,41.8,121775450,117933131,168697184
22,Bangladesh,BD,BGD,2018‑01‑01,80,104190480,106777785,159453001
23,Bangladesh,BD,BGD,2014‑01‑01,51.37,92007113,97373463,163654860
24,Bangladesh,BD,BGD,2008‑01‑01,85.26,81130973,87634867,151289991
25,Bangladesh,BD,BGD,2001‑01‑01,74.97,74946364,73445528,134477534
...,...,...,...,...,...,...,...,...
243,Vietnam,VN,VNM,2021‑01‑01,95.6,69523133,73616464,102789598
244,Vietnam,VN,VNM,2016‑01‑01,99.26,67500000,68142322,95261021
245,Vietnam,VN,VNM,2011‑01‑01,99.51,62270778,62610289,90549390
246,Vietnam,VN,VNM,2007‑01‑01,99.64,-,57459568,86518851
247,Vietnam,VN,VNM,2002‑01‑01,98.85,49783769,48823294,79939014

In [424]:
asia_voter_turnout['Country'].unique()

array(['Bangladesh', 'Bhutan', 'Cambodia', 'India', 'Indonesia', 'Japan',
       'South Korea', 'Laos', 'Malaysia', 'Maldives', 'Mongolia',
       'Myanmar', 'Nepal', 'Pakistan', 'Philippines', 'Singapore',
       'Sri Lanka', 'Taiwan', 'Thailand', 'Timor-Leste', 'Vietnam'],
      dtype=object)

In [425]:
asia_voter_turnout.columns.tolist()

['Country',
 'ISO2',
 'ISO3',
 'Date',
 'Parliamentary>Voter Turnout',
 'Parliamentary>Registration',
 'Parliamentary>Voting age population',
 'Parliamentary>Population']

In [426]:
print("In data but not in list:", set(asia_voter_turnout['Country'].unique()) - set(core_countries))
print("In list but not in data:", set(core_countries) - set(asia_voter_turnout['Country'].unique()))

In data but not in list: set()
In list but not in data: {'Hong Kong', 'China'}

In [427]:
asia_voter_turnout['Date'] = asia_voter_turnout['Date'].str.replace('‑', '-')

asia_voter_turnout['year'] = pd.to_datetime(asia_voter_turnout['Date']).dt.year

In [428]:
asia_voter_turnout

,Country,ISO2,ISO3,Date,Parliamentary>Voter Turnout,Parliamentary>Registration,Parliamentary>Voting age population,Parliamentary>Population,year
21,Bangladesh,BD,BGD,2024-01-07,41.8,121775450,117933131,168697184,2024
22,Bangladesh,BD,BGD,2018-01-01,80,104190480,106777785,159453001,2018
23,Bangladesh,BD,BGD,2014-01-01,51.37,92007113,97373463,163654860,2014
24,Bangladesh,BD,BGD,2008-01-01,85.26,81130973,87634867,151289991,2008
25,Bangladesh,BD,BGD,2001-01-01,74.97,74946364,73445528,134477534,2001
...,...,...,...,...,...,...,...,...,...
243,Vietnam,VN,VNM,2021-01-01,95.6,69523133,73616464,102789598,2021
244,Vietnam,VN,VNM,2016-01-01,99.26,67500000,68142322,95261021,2016
245,Vietnam,VN,VNM,2011-01-01,99.51,62270778,62610289,90549390,2011
246,Vietnam,VN,VNM,2007-01-01,99.64,-,57459568,86518851,2007
247,Vietnam,VN,VNM,2002-01-01,98.85,49783769,48823294,79939014,2002

In [429]:
asia_voter_turnout['Parliamentary>Voter Turnout'] = pd.to_numeric(asia_voter_turnout['Parliamentary>Voter Turnout'], errors='coerce')

In [430]:
asia_voter_turnout

,Country,ISO2,ISO3,Date,Parliamentary>Voter Turnout,Parliamentary>Registration,Parliamentary>Voting age population,Parliamentary>Population,year
21,Bangladesh,BD,BGD,2024-01-07,41.80,121775450,117933131,168697184,2024
22,Bangladesh,BD,BGD,2018-01-01,80.00,104190480,106777785,159453001,2018
23,Bangladesh,BD,BGD,2014-01-01,51.37,92007113,97373463,163654860,2014
24,Bangladesh,BD,BGD,2008-01-01,85.26,81130973,87634867,151289991,2008
25,Bangladesh,BD,BGD,2001-01-01,74.97,74946364,73445528,134477534,2001
...,...,...,...,...,...,...,...,...,...
243,Vietnam,VN,VNM,2021-01-01,95.60,69523133,73616464,102789598,2021
244,Vietnam,VN,VNM,2016-01-01,99.26,67500000,68142322,95261021,2016
245,Vietnam,VN,VNM,2011-01-01,99.51,62270778,62610289,90549390,2011
246,Vietnam,VN,VNM,2007-01-01,99.64,-,57459568,86518851,2007
247,Vietnam,VN,VNM,2002-01-01,98.85,49783769,48823294,79939014,2002

In [431]:
asia_voter_turnout.info()

<class 'pandas.core.frame.DataFrame'>
Index: 124 entries, 21 to 247
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              124 non-null    object
 1   ISO2                                 124 non-null    object
 2   ISO3                                 124 non-null    object
 3   Date                                 124 non-null    object
 4   Parliamentary>Voter Turnout          123 non-null    float64
 5   Parliamentary>Registration           124 non-null    object
 6   Parliamentary>Voting age population  124 non-null    int64
 7   Parliamentary>Population             124 non-null    object
 8   year                                 124 non-null    int32
dtypes: float64(1), int32(1), int64(1), object(6)
memory usage: 9.2+ KB

In [432]:
asia_voter_turnout.rename(columns={
    "Country": "country_name",
    "Parliamentary>Voter Turnout": "vap_turnout"}, inplace=True)

In [433]:
print(asia_voter_turnout[['country_name', 'year', 'vap_turnout']].dropna().head(10))

   country_name  year  vap_turnout
21   Bangladesh  2024        41.80
22   Bangladesh  2018        80.00
23   Bangladesh  2014        51.37
24   Bangladesh  2008        85.26
25   Bangladesh  2001        74.97
26       Bhutan  2024        65.60
27       Bhutan  2023        63.00
28       Bhutan  2018        71.46
29       Bhutan  2013        66.13
30       Bhutan  2008        79.45

In [434]:
voter_turnout_clean = asia_voter_turnout[[
    'country_name',
    'year',
    'vap_turnout']].copy()

In [435]:
voter_turnout_clean

    country_name  year  vap_turnout
21    Bangladesh  2024        41.80
22    Bangladesh  2018        80.00
23    Bangladesh  2014        51.37
24    Bangladesh  2008        85.26
25    Bangladesh  2001        74.97
..           ...   ...          ...
243      Vietnam  2021        95.60
244      Vietnam  2016        99.26
245      Vietnam  2011        99.51
246      Vietnam  2007        99.64
247      Vietnam  2002        98.85

[124 rows x 3 columns]

In [436]:
merged_from_2000 = merged_from_2000.merge(voter_turnout_clean, on=('country_name','year'), how='left')

In [437]:
merged_from_2000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 25 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   country_name                                      575 non-null    object
 1   country_text_id                                   575 non-null    object
 2   year                                              575 non-null    int64
 3   e_regiongeo                                       575 non-null    int64
 4   v2x_cspart                                        575 non-null    float64
 5   v2xcs_ccsi                                        575 non-null    float64
 6   v2x_partipdem                                     573 non-null    float64
 7   v2csprtcpt                                        575 non-null    float64
 8   v2x_polyarchy                                     575 non-null    float64
 9   v2x_libdem                                        575 non-null    float64
 10  v2x_api                                           575 non-null    float64
 11  v2xdd_dd                                          575 non-null    float64
 12  v2x_freexp_altinf                                 575 non-null    float64
 13  v2xel_frefair                                     575 non-null    float64
 14  v2x_egaldem                                       575 non-null    float64
 15  v2x_regime                                        575 non-null    float64
 16  v2smgovfilprc                                     575 non-null    float64
 17  v2smgovsmcenprc                                   575 non-null    float64
 18  v2smonper                                         575 non-null    float64
 19  GDP per capita (constant 2015 US$)                549 non-null    float64
 20  Individuals using the Internet (% of population)  516 non-null    float64
 21  Population, total                                 550 non-null    float64
 22  School enrollment, secondary (% gross)            412 non-null    float64
 23  Urban population (% of total population)          550 non-null    float64
 24  vap_turnout                                       121 non-null    float64
dtypes: float64(21), int64(2), object(2)
memory usage: 112.4+ KB

In [438]:
merged_from_2000 = merged_from_2000.sort_values(['country_name', 'year'])
merged_from_2000['vap_turnout'] = merged_from_2000.groupby('country_name')['vap_turnout'].ffill()
print(merged_from_2000['vap_turnout'].notna().sum())

468

In [439]:
merged_from_2000.info()

<class 'pandas.core.frame.DataFrame'>
Index: 575 entries, 50 to 124
Data columns (total 25 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   country_name                                      575 non-null    object
 1   country_text_id                                   575 non-null    object
 2   year                                              575 non-null    int64
 3   e_regiongeo                                       575 non-null    int64
 4   v2x_cspart                                        575 non-null    float64
 5   v2xcs_ccsi                                        575 non-null    float64
 6   v2x_partipdem                                     573 non-null    float64
 7   v2csprtcpt                                        575 non-null    float64
 8   v2x_polyarchy                                     575 non-null    float64
 9   v2x_libdem                                        575 non-null    float64
 10  v2x_api                                           575 non-null    float64
 11  v2xdd_dd                                          575 non-null    float64
 12  v2x_freexp_altinf                                 575 non-null    float64
 13  v2xel_frefair                                     575 non-null    float64
 14  v2x_egaldem                                       575 non-null    float64
 15  v2x_regime                                        575 non-null    float64
 16  v2smgovfilprc                                     575 non-null    float64
 17  v2smgovsmcenprc                                   575 non-null    float64
 18  v2smonper                                         575 non-null    float64
 19  GDP per capita (constant 2015 US$)                549 non-null    float64
 20  Individuals using the Internet (% of population)  516 non-null    float64
 21  Population, total                                 550 non-null    float64
 22  School enrollment, secondary (% gross)            412 non-null    float64
 23  Urban population (% of total population)          550 non-null    float64
 24  vap_turnout                                       468 non-null    float64
dtypes: float64(21), int64(2), object(2)
memory usage: 116.8+ KB

In [440]:
latest = merged_from_2000.groupby('country_name').last().reset_index()
latest = latest[latest['vap_turnout'].notna()]

In [441]:
latest

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,v2x_regime,v2smgovfilprc,v2smgovsmcenprc,v2smonper,GDP per capita (constant 2015 US$),Individuals using the Internet (% of population),"Population, total","School enrollment, secondary (% gross)",Urban population (% of total population),vap_turnout
0,Bangladesh,BGD,2024,14,0.580,0.582,0.090,1.335,0.201,0.068,...,1.0,-0.979,-3.439,-1.260,1941.278744,44.5027,1.735624e+08,64.299719,32.678320,41.80
1,Bhutan,BTN,2024,14,0.657,0.745,0.344,0.817,0.561,0.454,...,2.0,-0.904,-0.911,0.307,3480.513886,88.4260,7.915240e+05,86.181000,42.564525,65.60
2,Cambodia,KHM,2024,13,0.315,0.247,0.077,0.691,0.186,0.056,...,1.0,-2.374,-0.680,-1.713,2182.718439,60.7171,1.763880e+07,58.789323,40.872703,84.59
5,India,IND,2024,14,0.593,0.350,0.248,0.698,0.398,0.291,...,1.0,-0.993,-0.758,-0.463,2396.949992,55.9000,1.450936e+09,78.105807,35.378897,65.79
6,Indonesia,IDN,2024,13,0.795,0.812,0.318,1.709,0.483,0.326,...,1.0,0.696,0.114,0.488,4367.862666,72.7808,2.834879e+08,98.836444,58.750964,81.42
7,Japan,JPN,2024,12,0.683,0.955,0.526,0.420,0.820,0.734,...,3.0,1.721,1.663,1.279,37152.563600,86.9815,1.239754e+08,102.344437,92.190172,53.84
8,Laos,LAO,2024,13,0.247,0.103,0.116,-1.332,0.134,0.102,...,0.0,-1.200,-0.467,-3.282,2721.078107,63.6255,7.769819e+06,51.852360,39.555215,98.02
9,Malaysia,MYS,2024,13,0.777,0.725,0.315,1.265,0.517,0.362,...,2.0,0.317,0.157,0.799,11883.791277,98.0206,3.555767e+07,80.275741,76.917030,73.89
10,Maldives,MDV,2024,14,0.628,0.626,0.318,0.744,0.564,0.423,...,2.0,0.216,-0.223,0.236,11798.791369,84.6851,5.277990e+05,79.356530,41.998215,73.91
11,Mongolia,MNG,2024,12,0.575,0.689,0.249,0.259,0.496,0.389,...,1.0,0.775,0.152,0.272,4626.796096,83.0162,3.524788e+06,96.818120,70.956604,69.83
12,Myanmar,MMR,2024,13,0.134,0.126,0.093,-1.025,0.083,0.016,...,0.0,-1.673,-2.951,-2.385,1158.479281,58.5357,5.450009e+07,77.019150,30.449908,71.89
13,Nepal,NPL,2024,14,0.770,0.808,0.427,2.097,0.669,0.522,...,2.0,-0.447,-1.127,0.189,1179.812728,55.7716,2.965105e+07,90.387846,66.772343,61.35
14,Pakistan,PAK,2024,14,0.652,0.649,0.204,1.076,0.313,0.199,...,1.0,-1.133,-0.510,0.623,1634.567353,27.3759,2.512692e+08,48.280502,39.173437,47.28
15,Philippines,PHL,2024,13,0.681,0.773,0.284,1.378,0.435,0.308,...,1.0,0.525,0.368,0.563,3925.304870,83.7661,1.158437e+08,85.294509,55.452098,83.83
16,Singapore,SGP,2024,13,0.386,0.403,0.112,-0.252,0.414,0.343,...,1.0,-0.657,-0.617,-1.155,67706.833615,94.3776,6.036860e+06,103.082802,100.000000,95.81
17,South Korea,KOR,2024,12,0.814,0.770,0.485,1.410,0.729,0.631,...,2.0,0.608,0.631,2.114,37048.426400,97.8956,5.175106e+07,96.298393,81.168253,66.97
18,Sri Lanka,LKA,2024,14,0.767,0.665,0.431,2.636,0.664,0.486,...,2.0,-0.111,0.770,1.287,4186.498664,51.2000,2.191600e+07,87.953407,20.299700,68.93
19,Taiwan,TWN,2024,12,0.933,0.907,0.621,2.950,0.800,0.700,...,3.0,0.438,0.646,1.970,NaN,NaN,NaN,NaN,NaN,71.78
20,Thailand,THA,2024,13,0.699,0.640,0.186,1.015,0.389,0.289,...,1.0,-0.868,-0.573,0.341,6574.461094,90.8672,7.166801e+07,92.507326,61.868934,75.71
21,Timor-Leste,TLS,2024,13,0.700,0.913,0.455,1.394,0.733,0.549,...,2.0,1.687,1.427,0.708,1149.218883,34.0207,1.400638e+06,84.741040,28.664107,79.28
22,Vietnam,VNM,2024,13,0.674,0.142,0.157,0.947,0.174,0.124,...,0.0,-2.721,-1.474,-2.140,4017.746041,84.1500,1.009877e+08,93.412343,38.490070,95.60

In [442]:
merged_from_2000

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,v2x_regime,v2smgovfilprc,v2smgovsmcenprc,v2smonper,GDP per capita (constant 2015 US$),Individuals using the Internet (% of population),"Population, total","School enrollment, secondary (% gross)",Urban population (% of total population),vap_turnout
50,Bangladesh,BGD,2000,14,0.748,0.769,0.230,2.031,0.511,0.275,...,2.0,0.203,-0.815,0.152,620.560473,0.071039,134544304.0,46.721001,23.314511,NaN
51,Bangladesh,BGD,2001,14,0.748,0.717,0.226,2.031,0.504,0.268,...,2.0,0.203,-0.815,0.152,641.288923,0.129808,136805810.0,48.460972,23.699921,74.97
52,Bangladesh,BGD,2002,14,0.767,0.736,0.209,2.031,0.463,0.235,...,1.0,0.203,-0.815,0.152,655.672139,0.139920,138933658.0,49.619949,24.113238,74.97
53,Bangladesh,BGD,2003,14,0.767,0.737,0.211,2.031,0.474,0.239,...,1.0,0.203,-0.815,0.152,676.826252,0.163878,140970351.0,49.525902,24.552556,74.97
54,Bangladesh,BGD,2004,14,0.767,0.737,0.209,2.031,0.474,0.233,...,1.0,0.203,-0.815,0.152,702.656357,0.199036,142902856.0,46.308430,25.009481,74.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,Vietnam,VNM,2020,13,0.689,0.262,0.181,1.055,0.211,0.108,...,1.0,-2.033,-1.488,-2.133,3303.169498,70.300000,98079191.0,93.192139,35.570668,99.26
121,Vietnam,VNM,2021,13,0.682,0.261,0.169,0.947,0.170,0.110,...,0.0,-1.995,-1.488,-1.836,3358.217348,74.210000,98935098.0,92.769021,36.654066,95.60
122,Vietnam,VNM,2022,13,0.609,0.170,0.159,0.947,0.153,0.109,...,0.0,-2.150,-1.488,-1.658,3617.663115,78.590000,99680655.0,93.412343,37.547852,95.60
123,Vietnam,VNM,2023,13,0.695,0.143,0.166,0.947,0.148,0.113,...,0.0,-2.721,-1.488,-2.140,3775.463756,78.080000,100352192.0,NaN,38.129890,95.60
124,Vietnam,VNM,2024,13,0.674,0.142,0.157,0.947,0.174,0.124,...,0.0,-2.721,-1.474,-2.140,4017.746041,84.150000,100987686.0,NaN,38.490070,95.60

In [443]:
# max year in the merged dataset (wdi and V-dem)

max_vdem_year = merged_from_2000['year'].max()
max_vdem_year

2024

In [444]:
# limiting elections within analysis by max years in V-dem and wdi datasets

valid_elections = asia_voter_turnout[asia_voter_turnout['year'] <= max_vdem_year]

In [445]:
valid_elections

,country_name,ISO2,ISO3,Date,vap_turnout,Parliamentary>Registration,Parliamentary>Voting age population,Parliamentary>Population,year
21,Bangladesh,BD,BGD,2024-01-07,41.80,121775450,117933131,168697184,2024
22,Bangladesh,BD,BGD,2018-01-01,80.00,104190480,106777785,159453001,2018
23,Bangladesh,BD,BGD,2014-01-01,51.37,92007113,97373463,163654860,2014
24,Bangladesh,BD,BGD,2008-01-01,85.26,81130973,87634867,151289991,2008
25,Bangladesh,BD,BGD,2001-01-01,74.97,74946364,73445528,134477534,2001
...,...,...,...,...,...,...,...,...,...
243,Vietnam,VN,VNM,2021-01-01,95.60,69523133,73616464,102789598,2021
244,Vietnam,VN,VNM,2016-01-01,99.26,67500000,68142322,95261021,2016
245,Vietnam,VN,VNM,2011-01-01,99.51,62270778,62610289,90549390,2011
246,Vietnam,VN,VNM,2007-01-01,99.64,-,57459568,86518851,2007
247,Vietnam,VN,VNM,2002-01-01,98.85,49783769,48823294,79939014,2002

In [446]:
election_years_2024 = valid_elections.groupby('country_name')['year'].max().reset_index()
election_years_2024.columns = ['country_name','election_year']

In [447]:
election_years_2024

   country_name  election_year
0    Bangladesh           2024
1        Bhutan           2024
2      Cambodia           2023
3         India           2024
4     Indonesia           2024
5         Japan           2024
6          Laos           2021
7      Malaysia           2022
8      Maldives           2024
9      Mongolia           2024
10      Myanmar           2020
11        Nepal           2022
12     Pakistan           2024
13  Philippines           2022
14    Singapore           2020
15  South Korea           2024
16    Sri Lanka           2024
17       Taiwan           2024
18     Thailand           2023
19  Timor-Leste           2023
20      Vietnam           2021

In [449]:
latest = merged_from_2000.merge(election_years_2024, on='country_name')
latest = latest[latest['year'] == latest['election_year']]

In [550]:
latest

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,Individuals using the Internet (% of population),"Population, total","School enrollment, secondary (% gross)",Urban population (% of total population),vap_turnout,election_year,turnout_z,cspart_z,year_label,regime_label
24,Bangladesh,BGD,2024,14,0.580,0.582,0.090,1.335,0.201,0.068,...,NaN,1.735624e+08,64.299719,32.678320,41.80,2024,-2.151676,-0.419870,2024,Electoral Autocracy
49,Bhutan,BTN,2024,14,0.657,0.745,0.344,0.817,0.561,0.454,...,NaN,7.915240e+05,86.181000,42.564525,65.60,2024,-0.495470,0.048357,2024,Electoral Democracy
73,Cambodia,KHM,2023,13,0.315,0.247,0.077,0.691,0.190,0.054,...,60.7171,1.742388e+07,56.786473,40.629079,84.59,2023,0.826015,-2.031304,2023,Electoral Autocracy
99,India,IND,2024,14,0.593,0.350,0.248,0.698,0.398,0.291,...,NaN,1.450936e+09,78.105807,35.378897,65.79,2024,-0.482248,-0.340819,2024,Electoral Autocracy
124,Indonesia,IDN,2024,13,0.795,0.812,0.318,1.709,0.483,0.326,...,72.7808,2.834879e+08,98.836444,58.750964,81.42,2024,0.605420,0.887519,2024,Electoral Autocracy
149,Japan,JPN,2024,12,0.683,0.955,0.526,0.420,0.820,0.734,...,NaN,1.239754e+08,NaN,92.190172,53.84,2024,-1.313831,0.206460,2024,Liberal Democracy
171,Laos,LAO,2021,13,0.303,0.155,0.121,-1.111,0.134,0.094,...,62.0000,7.453194e+06,59.853060,37.338778,98.02,2021,1.760589,-2.104274,2021,Closed Autocracy
197,Malaysia,MYS,2022,13,0.775,0.708,0.276,1.265,0.460,0.317,...,97.3986,3.469549e+07,78.834199,75.974136,73.89,2022,0.081419,0.765901,2022,Electoral Autocracy
224,Maldives,MDV,2024,14,0.628,0.626,0.318,0.744,0.564,0.423,...,NaN,5.277990e+05,NaN,41.998215,73.91,2024,0.082810,-0.127988,2024,Electoral Democracy
249,Mongolia,MNG,2024,12,0.575,0.689,0.249,0.259,0.496,0.389,...,NaN,3.524788e+06,NaN,70.956604,69.83,2024,-0.201111,-0.450275,2024,Electoral Autocracy
270,Myanmar,MMR,2020,13,0.671,0.625,0.268,1.253,0.427,0.261,...,45.4477,5.301652e+07,NaN,30.159305,71.89,2020,-0.057758,0.133490,2020,Electoral Autocracy
297,Nepal,NPL,2022,14,0.872,0.849,0.422,2.603,0.630,0.497,...,53.8878,2.971544e+07,84.102648,66.299297,61.35,2022,-0.791221,1.355747,2022,Electoral Democracy
324,Pakistan,PAK,2024,14,0.652,0.649,0.204,1.076,0.313,0.199,...,NaN,2.512692e+08,48.280502,39.173437,47.28,2024,-1.770331,0.017953,2024,Electoral Autocracy
347,Philippines,PHL,2022,13,0.709,0.744,0.287,1.378,0.430,0.288,...,75.2111,1.139643e+08,92.291271,54.790234,83.83,2022,0.773128,0.364563,2022,Electoral Autocracy
370,Singapore,SGP,2020,13,0.329,0.403,0.102,-0.252,0.400,0.325,...,92.0043,5.685807e+06,103.115839,100.000000,95.81,2020,1.606798,-1.946171,2020,Electoral Autocracy
399,South Korea,KOR,2024,12,0.814,0.770,0.485,1.410,0.729,0.631,...,97.8956,5.175106e+07,NaN,81.168253,66.97,2024,-0.400134,1.003056,2024,Electoral Democracy
424,Sri Lanka,LKA,2024,14,0.767,0.665,0.431,2.636,0.664,0.486,...,NaN,2.191600e+07,NaN,20.299700,68.93,2024,-0.263740,0.717254,2024,Electoral Democracy
449,Taiwan,TWN,2024,12,0.933,0.907,0.621,2.950,0.800,0.700,...,NaN,NaN,NaN,NaN,71.78,2024,-0.065413,1.726680,2024,Liberal Democracy
473,Thailand,THA,2023,13,0.597,0.579,0.142,0.784,0.289,0.240,...,89.5353,7.170244e+07,93.335632,60.934193,75.71,2023,0.208070,-0.316495,2023,Electoral Autocracy
498,Timor-Leste,TLS,2023,13,0.700,0.897,0.442,1.394,0.712,0.525,...,34.0207,1.384286e+06,NaN,28.595472,79.28,2023,0.456500,0.309835,2023,Electoral Democracy
521,Vietnam,VNM,2021,13,0.682,0.261,0.169,0.947,0.170,0.110,...,74.2100,9.893510e+07,92.769021,36.654066,95.60,2021,1.592184,0.200379,2021,Closed Autocracy

In [452]:
print(latest[['country_name', 'year', 'vap_turnout', 'v2x_cspart']].sort_values('vap_turnout').to_string())

    country_name  year  vap_turnout  v2x_cspart
24    Bangladesh  2024        41.80       0.580
324     Pakistan  2024        47.28       0.652
149        Japan  2024        53.84       0.683
297        Nepal  2022        61.35       0.872
49        Bhutan  2024        65.60       0.657
99         India  2024        65.79       0.593
399  South Korea  2024        66.97       0.814
424    Sri Lanka  2024        68.93       0.767
249     Mongolia  2024        69.83       0.575
449       Taiwan  2024        71.78       0.933
270      Myanmar  2020        71.89       0.671
197     Malaysia  2022        73.89       0.775
224     Maldives  2024        73.91       0.628
473     Thailand  2023        75.71       0.597
498  Timor-Leste  2023        79.28       0.700
124    Indonesia  2024        81.42       0.795
347  Philippines  2022        83.83       0.709
73      Cambodia  2023        84.59       0.315
521      Vietnam  2021        95.60       0.682
370    Singapore  2020        95.81       0.329
171         Laos  2021        98.02       0.303

In [552]:
merged_from_2000.to_csv('processed_data.csv',index=False)
latest.to_csv('latest_election_data.csv', index=False)

In [471]:
from lets_plot import *

In [553]:
regime_labels = {0: 'Closed Autocracy', 1: 'Electoral Autocracy', 
                 2: 'Electoral Democracy', 3: 'Liberal Democracy'}

latest['regime_label'] = latest['v2x_regime'].map(regime_labels)

In [554]:
latest

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,Individuals using the Internet (% of population),"Population, total","School enrollment, secondary (% gross)",Urban population (% of total population),vap_turnout,election_year,turnout_z,cspart_z,year_label,regime_label
24,Bangladesh,BGD,2024,14,0.580,0.582,0.090,1.335,0.201,0.068,...,NaN,1.735624e+08,64.299719,32.678320,41.80,2024,-2.151676,-0.419870,2024,Electoral Autocracy
49,Bhutan,BTN,2024,14,0.657,0.745,0.344,0.817,0.561,0.454,...,NaN,7.915240e+05,86.181000,42.564525,65.60,2024,-0.495470,0.048357,2024,Electoral Democracy
73,Cambodia,KHM,2023,13,0.315,0.247,0.077,0.691,0.190,0.054,...,60.7171,1.742388e+07,56.786473,40.629079,84.59,2023,0.826015,-2.031304,2023,Electoral Autocracy
99,India,IND,2024,14,0.593,0.350,0.248,0.698,0.398,0.291,...,NaN,1.450936e+09,78.105807,35.378897,65.79,2024,-0.482248,-0.340819,2024,Electoral Autocracy
124,Indonesia,IDN,2024,13,0.795,0.812,0.318,1.709,0.483,0.326,...,72.7808,2.834879e+08,98.836444,58.750964,81.42,2024,0.605420,0.887519,2024,Electoral Autocracy
149,Japan,JPN,2024,12,0.683,0.955,0.526,0.420,0.820,0.734,...,NaN,1.239754e+08,NaN,92.190172,53.84,2024,-1.313831,0.206460,2024,Liberal Democracy
171,Laos,LAO,2021,13,0.303,0.155,0.121,-1.111,0.134,0.094,...,62.0000,7.453194e+06,59.853060,37.338778,98.02,2021,1.760589,-2.104274,2021,Closed Autocracy
197,Malaysia,MYS,2022,13,0.775,0.708,0.276,1.265,0.460,0.317,...,97.3986,3.469549e+07,78.834199,75.974136,73.89,2022,0.081419,0.765901,2022,Electoral Autocracy
224,Maldives,MDV,2024,14,0.628,0.626,0.318,0.744,0.564,0.423,...,NaN,5.277990e+05,NaN,41.998215,73.91,2024,0.082810,-0.127988,2024,Electoral Democracy
249,Mongolia,MNG,2024,12,0.575,0.689,0.249,0.259,0.496,0.389,...,NaN,3.524788e+06,NaN,70.956604,69.83,2024,-0.201111,-0.450275,2024,Electoral Autocracy
270,Myanmar,MMR,2020,13,0.671,0.625,0.268,1.253,0.427,0.261,...,45.4477,5.301652e+07,NaN,30.159305,71.89,2020,-0.057758,0.133490,2020,Electoral Autocracy
297,Nepal,NPL,2022,14,0.872,0.849,0.422,2.603,0.630,0.497,...,53.8878,2.971544e+07,84.102648,66.299297,61.35,2022,-0.791221,1.355747,2022,Electoral Democracy
324,Pakistan,PAK,2024,14,0.652,0.649,0.204,1.076,0.313,0.199,...,NaN,2.512692e+08,48.280502,39.173437,47.28,2024,-1.770331,0.017953,2024,Electoral Autocracy
347,Philippines,PHL,2022,13,0.709,0.744,0.287,1.378,0.430,0.288,...,75.2111,1.139643e+08,92.291271,54.790234,83.83,2022,0.773128,0.364563,2022,Electoral Autocracy
370,Singapore,SGP,2020,13,0.329,0.403,0.102,-0.252,0.400,0.325,...,92.0043,5.685807e+06,103.115839,100.000000,95.81,2020,1.606798,-1.946171,2020,Electoral Autocracy
399,South Korea,KOR,2024,12,0.814,0.770,0.485,1.410,0.729,0.631,...,97.8956,5.175106e+07,NaN,81.168253,66.97,2024,-0.400134,1.003056,2024,Electoral Democracy
424,Sri Lanka,LKA,2024,14,0.767,0.665,0.431,2.636,0.664,0.486,...,NaN,2.191600e+07,NaN,20.299700,68.93,2024,-0.263740,0.717254,2024,Electoral Democracy
449,Taiwan,TWN,2024,12,0.933,0.907,0.621,2.950,0.800,0.700,...,NaN,NaN,NaN,NaN,71.78,2024,-0.065413,1.726680,2024,Liberal Democracy
473,Thailand,THA,2023,13,0.597,0.579,0.142,0.784,0.289,0.240,...,89.5353,7.170244e+07,93.335632,60.934193,75.71,2023,0.208070,-0.316495,2023,Electoral Autocracy
498,Timor-Leste,TLS,2023,13,0.700,0.897,0.442,1.394,0.712,0.525,...,34.0207,1.384286e+06,NaN,28.595472,79.28,2023,0.456500,0.309835,2023,Electoral Democracy
521,Vietnam,VNM,2021,13,0.682,0.261,0.169,0.947,0.170,0.110,...,74.2100,9.893510e+07,92.769021,36.654066,95.60,2021,1.592184,0.200379,2021,Closed Autocracy

In [555]:
latest['year_label'] = latest['year'].astype(str)

In [710]:
cv_vt_scatter = (
    ggplot(latest, aes(x='v2x_cspart',y='vap_turnout'))
    + geom_point(aes(color='regime_label'),
                 tooltips = layer_tooltips()
                 .line('@country_name')
                 .line('Turnout: @vap_turnout')
                 .line('Civic Participation: @v2x_cspart')
                 .line('Year: @year_label'),
                 size=6)
    + labs(
        title = 'Relationship between Civil Society Participation Index & Voter Turnout',
        subtitle = 'Higher turnout does not mean deeper civic engagement',
        x = 'Civil Society Participation Index (year of most recent election)',
        y = 'Voter Turnout (most recent election)',
        caption='Sources: V-Dem v15, IDEA Voter Turnout Database. \n Values shown for each country\'s most recent parliamentary election year.')
    + theme_light()
    + scale_y_continuous(limits = (0,100))
    + scale_x_continuous(limits = (0,1))
    + theme(plot_margin=[40, 20, 20, 20],
            text=element_text(family='Avenir Next'),
            plot_caption=element_text(size=8, color='grey', margin=[20,0,0,0]),
            legend_title=element_text(size=12, face='bold'),
            legend_text=element_text(size=11),
            plot_title=element_text(size=16, face='bold', margin=[0,0,10,0]),
            plot_subtitle=element_text(size=12, face='italic', margin=[0,0,10,0]),
            axis_title=element_text(size=12, face='italic'),
            plot_background=element_rect(fill='white'),
            panel_background=element_rect(fill='white'),
            panel_grid_major=element_line(color='#EBEBEB', size=0.5))
    + ggsize(800, 500)
    + scale_color_manual(
        name = 'Regime Type',
        values = {
            'Liberal Democracy': '#457B9D',
            'Electoral Democracy': '#2A9D8F',
            'Electoral Autocracy': '#E9C46A',
            'Closed Autocracy': '#E63946'
        }
    )
)
cv_vt_scatter

In [590]:
from sklearn.preprocessing import StandardScaler

In [591]:
scaler = StandardScaler()
latest[['turnout_z', 'cspart_z']] = scaler.fit_transform(
    latest[['vap_turnout', 'v2x_cspart']]
)

In [592]:
latest

,country_name,country_text_id,year,e_regiongeo,v2x_cspart,v2xcs_ccsi,v2x_partipdem,v2csprtcpt,v2x_polyarchy,v2x_libdem,...,Individuals using the Internet (% of population),"Population, total","School enrollment, secondary (% gross)",Urban population (% of total population),vap_turnout,election_year,turnout_z,cspart_z,year_label,regime_label
24,Bangladesh,BGD,2024,14,0.580,0.582,0.090,1.335,0.201,0.068,...,NaN,1.735624e+08,64.299719,32.678320,41.80,2024,-2.151676,-0.419870,2024,Electoral Autocracy
49,Bhutan,BTN,2024,14,0.657,0.745,0.344,0.817,0.561,0.454,...,NaN,7.915240e+05,86.181000,42.564525,65.60,2024,-0.495470,0.048357,2024,Electoral Democracy
73,Cambodia,KHM,2023,13,0.315,0.247,0.077,0.691,0.190,0.054,...,60.7171,1.742388e+07,56.786473,40.629079,84.59,2023,0.826015,-2.031304,2023,Electoral Autocracy
99,India,IND,2024,14,0.593,0.350,0.248,0.698,0.398,0.291,...,NaN,1.450936e+09,78.105807,35.378897,65.79,2024,-0.482248,-0.340819,2024,Electoral Autocracy
124,Indonesia,IDN,2024,13,0.795,0.812,0.318,1.709,0.483,0.326,...,72.7808,2.834879e+08,98.836444,58.750964,81.42,2024,0.605420,0.887519,2024,Electoral Autocracy
149,Japan,JPN,2024,12,0.683,0.955,0.526,0.420,0.820,0.734,...,NaN,1.239754e+08,NaN,92.190172,53.84,2024,-1.313831,0.206460,2024,Liberal Democracy
171,Laos,LAO,2021,13,0.303,0.155,0.121,-1.111,0.134,0.094,...,62.0000,7.453194e+06,59.853060,37.338778,98.02,2021,1.760589,-2.104274,2021,Closed Autocracy
197,Malaysia,MYS,2022,13,0.775,0.708,0.276,1.265,0.460,0.317,...,97.3986,3.469549e+07,78.834199,75.974136,73.89,2022,0.081419,0.765901,2022,Electoral Autocracy
224,Maldives,MDV,2024,14,0.628,0.626,0.318,0.744,0.564,0.423,...,NaN,5.277990e+05,NaN,41.998215,73.91,2024,0.082810,-0.127988,2024,Electoral Democracy
249,Mongolia,MNG,2024,12,0.575,0.689,0.249,0.259,0.496,0.389,...,NaN,3.524788e+06,NaN,70.956604,69.83,2024,-0.201111,-0.450275,2024,Electoral Autocracy
270,Myanmar,MMR,2020,13,0.671,0.625,0.268,1.253,0.427,0.261,...,45.4477,5.301652e+07,NaN,30.159305,71.89,2020,-0.057758,0.133490,2020,Electoral Autocracy
297,Nepal,NPL,2022,14,0.872,0.849,0.422,2.603,0.630,0.497,...,53.8878,2.971544e+07,84.102648,66.299297,61.35,2022,-0.791221,1.355747,2022,Electoral Democracy
324,Pakistan,PAK,2024,14,0.652,0.649,0.204,1.076,0.313,0.199,...,NaN,2.512692e+08,48.280502,39.173437,47.28,2024,-1.770331,0.017953,2024,Electoral Autocracy
347,Philippines,PHL,2022,13,0.709,0.744,0.287,1.378,0.430,0.288,...,75.2111,1.139643e+08,92.291271,54.790234,83.83,2022,0.773128,0.364563,2022,Electoral Autocracy
370,Singapore,SGP,2020,13,0.329,0.403,0.102,-0.252,0.400,0.325,...,92.0043,5.685807e+06,103.115839,100.000000,95.81,2020,1.606798,-1.946171,2020,Electoral Autocracy
399,South Korea,KOR,2024,12,0.814,0.770,0.485,1.410,0.729,0.631,...,97.8956,5.175106e+07,NaN,81.168253,66.97,2024,-0.400134,1.003056,2024,Electoral Democracy
424,Sri Lanka,LKA,2024,14,0.767,0.665,0.431,2.636,0.664,0.486,...,NaN,2.191600e+07,NaN,20.299700,68.93,2024,-0.263740,0.717254,2024,Electoral Democracy
449,Taiwan,TWN,2024,12,0.933,0.907,0.621,2.950,0.800,0.700,...,NaN,NaN,NaN,NaN,71.78,2024,-0.065413,1.726680,2024,Liberal Democracy
473,Thailand,THA,2023,13,0.597,0.579,0.142,0.784,0.289,0.240,...,89.5353,7.170244e+07,93.335632,60.934193,75.71,2023,0.208070,-0.316495,2023,Electoral Autocracy
498,Timor-Leste,TLS,2023,13,0.700,0.897,0.442,1.394,0.712,0.525,...,34.0207,1.384286e+06,NaN,28.595472,79.28,2023,0.456500,0.309835,2023,Electoral Democracy
521,Vietnam,VNM,2021,13,0.682,0.261,0.169,0.947,0.170,0.110,...,74.2100,9.893510e+07,92.769021,36.654066,95.60,2021,1.592184,0.200379,2021,Closed Autocracy

In [669]:
latest_dumbbell = latest.copy()

In [670]:
latest_dumbbell['gap'] = latest_dumbbell['turnout_z'] - latest_dumbbell['cspart_z']

In [671]:
latest_dumbbell = latest_dumbbell.sort_values(by='gap')
latest_dumbbell['country_name'] = pd.Categorical(
    latest_dumbbell['country_name'],
    categories=latest_dumbbell['country_name'],
    ordered=True)

In [673]:
latest_dumbbell['turnout_label'] = 'Voter Turnout'
latest_dumbbell['cspart_label'] = 'Civic Participation'

In [708]:
cv_vt_dumbbell = (
    ggplot(latest_dumbbell, aes(y='country_name'))
    + geom_point(aes(x='turnout_z', color='turnout_label'), size = 5,
                 tooltips = layer_tooltips()
                 .line('Turnout: @vap_turnout')
                 .line('Year: @year_label'))
    + geom_point(aes(x='cspart_z', color='cspart_label'), size = 5,
                 tooltips = layer_tooltips()
                 .line('Civic Participation: @v2x_cspart')
                 .line('Year: @year_label'))
    + geom_segment(aes(x='turnout_z', xend='cspart_z', y='country_name', yend='country_name'),
                   color='grey', alpha=0.5, size=1)
    + labs(title = 'Gap between Voter Turnout and Civic Participation',
           x = 'Voter Turnout and Civil Society Participation (standardised)',
           y = 'Country',
           caption='Sources: V-Dem v15, IDEA Voter Turnout Database. \n Values shown for each country\'s most recent parliamentary election year. ' \
           '\n Civic Participation Index and Voter Turnout have been standardised to the same scale for comparison')
    + ggsize(700, 700)
    + theme_light()
    + theme(plot_margin=[20, 10, 10, 10], 
        text=element_text(family='Avenir Next'),
        plot_caption=element_text(size=8, color='grey', margin=[20,0,0,0]),
        legend_title=element_text(size=12, face='bold'),
        legend_text=element_text(size=11),
        plot_title=element_text(size=16, face='bold', margin=[0,0,10,0]),
        plot_subtitle=element_text(size=12, face='italic', margin=[0,0,10,0]),
        axis_title=element_text(size=12, face='italic'),
        axis_text=element_text(size=10),
        panel_grid_major_x=element_line(color='#EBEBEB', size=0.3),
        panel_grid_major_y=element_blank(),
        panel_grid_minor=element_blank(),
        panel_border=element_blank())
    + scale_color_manual(
        name = 'Legend',
        values = {
            'Voter Turnout': '#264653',
            'Civic Participation': '#F4A261'
        }
    ))

cv_vt_dumbbell